spring.application.name=015
spring.data.mongodb.host=localhost
spring.data.mongodb.port = 8080
spring.data.mongodb.database =${MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URI}

spring.security.user.name=haro
spring.security.user.password=haro123